sudo: required
dist: trusty
language: generic

addons:
  apt:
    sources:
    - hvr-ghc
    - sourceline: 'ppa:hvr/ghcjs'
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://deb.nodesource.com/node_6.x trusty main'
      key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    packages:
    - cabal-install-head
    - ghc-8.2.2
    - ghcjs-8.2
    - alex-3.1.4
    - happy-1.19.5

cache:
  bundler: false
  directories:
  - $HOME/.ghc/
  - $HOME/.ghcjs/
  - $HOME/.cabal/bin
  - $HOME/.cabal/share
  - $HOME/.cabal/lib

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/alex/3.1.4/bin:$PATH
    - export PATH=/opt/happy/1.19.5/bin:$PATH
    - export PATH=/opt/ghc/bin:$PATH
    - export PATH=/opt/ghcjs/8.2/bin:$PATH
    - export PATH=$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH
    - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share
    - rm -f ~/.cabal/config
    - cabal update # to ensure the config exists
    - 'fgrep hackage-ghcjs-overlay.nomeata.de/ $HOME/.cabal/config ||
      echo -e "repository ghcjs-overlay\n url: http://hackage-ghcjs-overlay.nomeata.de/\n secure: True\n root-keys:\n key-threshold: 0" >> ~/.cabal/config'
    - cat ~/.cabal/config
    - cabal update

jobs:
 include:
   - stage: install ghc dependencies
     if: type = api
     install:
      - make prepare-ghc
     script:
       - ghc-pkg list
   - stage: install ghcjs dependencies
     if: type = api
     install:
      - make prepare-ghcjs
     script:
       - ghcjs-pkg list
   - stage: build, test and deploy
     install:
       - make prepare
     script:
       - make
       - make test

     before_deploy:
       - ./deploy gh-page

     deploy:
       provider: pages
       local-dir: gh-page
       fqdn: incredible.pm
       keep-history: true
       allow-empty-commit: true
       skip-cleanup: true
       github-token: $GITHUB_TOKEN
       on:
         branch: master

before_cache:
  - rm -rf $HOME/.ghcjs/*/ghcjs/ghcjs-boot/
  - du -sh $HOME/.ghcjs $HOME/.ghc $HOME/.cabal/bin $HOME/.cabal/lib $HOME/.cabal/share



